import { modestify, type Design, type Outfit } from './modesty';
import { EXTENDED_DESIGNS } from './outfits-extended';

/**
 * The wardrobe. Each entry is a *reference design* described as the inspiration looks (see
 * docs/ART_BIBLE.md §2) — some are deliberately not covering, e.g. the dirndl or the tea dress —
 * and modestify() merges in sleeves, trousers and a headscarf. Never hand-write an Outfit.
 */
const DESIGNS: Design[] = [
  // ───────────── Girl ─────────────
  // The travellers' everyday default (owner's choice): a mid-length kurti / kurta with jeans.
  { id: 'g-kurti-jeans', who: 'girl', name: 'Pink Kurti & Jeans', culture: 'Modern India', top: 'kurta', topColor: '#f9c5d9', trim: '#ffffff', sleeve: 'full', hem: 'thigh', lower: 'trousers', lowerColor: '#9dbbe0', head: { style: 'hijab', color: '#fff0f5' }, outer: { style: 'dupatta', color: '#ffffff' }, pattern: 'floral', detail: { legs: 'flared', hemFlare: 0.46, ribbon: '#ffffff' }, note: 'Half-thigh light-pink kurti with a wide hem, white floral buti and a white ribbon bow, flared light-wash jeans, a white stole and blush headscarf.' },
  { id: 'b-kurta-jeans', who: 'boy', name: 'Blue Kurta & Pink Jeans', culture: 'Modern India', top: 'kurta', topColor: '#8fbfe8', trim: '#ffffff', sleeve: 'full', hem: 'thigh', lower: 'trousers', lowerColor: '#f8c9da', head: { style: 'hair', color: '#1a1410' }, pattern: 'bands', detail: { legs: 'bell', hemFlare: 0.1, cuffs: '#ffffff', buttons: '#ffffff' }, note: 'Half-thigh light-blue kurta with a narrow hem, white thread-work bands and deep white buttoned cuffs, light-pink bell-bottom jeans.' },
  // The celebration evening (special event): made in the castle's wardrobe, just for her.
  { id: 'g-starlight-gown', who: 'girl', name: 'Starlight Gown', culture: 'Celebration', top: 'gown', topColor: '#f7a6cf', trim: '#ffffff', sleeve: 'full', sleeveShape: 'bell', hem: 'floor', lower: 'skirt', lowerColor: '#f59bc8', head: { style: 'hijab', color: '#fcd9ec' }, outer: { style: 'cape', color: '#fde6f2' }, pattern: 'floral', detail: { rainbow: true, ribbon: '#ffffff', glow: 0.32, vines: true }, note: 'A floor-length pink evening gown that glows softly, with rainbow branches and blossoms winding down the skirt, flowers everywhere, rainbow bands at the hem, a white ribbon bow and a soft cape.' },
  { id: 'b-celebration', who: 'boy', name: 'Midnight Sherwani', culture: 'Celebration', top: 'sherwani', topColor: '#4a64b5', trim: '#ffffff', sleeve: 'full', hem: 'knee', lower: 'trousers', lowerColor: '#f3eefe', head: { style: 'hair', color: '#1a1410' }, pattern: 'stars', detail: { cuffs: '#ffffff', buttons: '#ffffff' }, note: 'A starry royal-blue sherwani with white trim and cuffs, for her evening.' },
  { id: 'g-meadow', who: 'girl', name: 'Wanderer', culture: 'Meadow', top: 'tunic', topColor: '#f4d6a0', trim: '#e0865a', sleeve: 'full', hem: 'ankle', lower: 'skirt', lowerColor: '#8fb58a', head: { style: 'hijab', color: '#f7efe0' }, outer: { style: 'cape', color: '#e0865a' }, pattern: 'bands' },
  { id: 'g-kimono', who: 'girl', name: 'Kimono & Hakama', culture: 'Japan', top: 'kimono', topColor: '#f3b8c8', trim: '#b3264a', sleeve: 'full', sleeveShape: 'wide', hem: 'ankle', lower: 'hakama', lowerColor: '#5a2a4a', head: { style: 'hijab', color: '#fff2f5' }, pattern: 'floral' },
  { id: 'g-hanbok', who: 'girl', name: 'Hanbok', culture: 'Korea', top: 'jeogori', topColor: '#fff4d6', trim: '#d9467a', sleeve: 'full', hem: 'floor', lower: 'skirt', lowerColor: '#e8577f', head: { style: 'hood', color: '#7a4fb0' }, pattern: 'bands' },
  { id: 'g-hanfu', who: 'girl', name: 'Hanfu Ruqun', culture: 'China', top: 'hanfu', topColor: '#bfe3e0', trim: '#2f6f73', sleeve: 'full', sleeveShape: 'wide', hem: 'floor', lower: 'skirt', lowerColor: '#f2c6d0', head: { style: 'hijab-wrap', color: '#e9f5f3' }, outer: { style: 'sash', color: '#c9a7e8' }, pattern: 'floral' },
  { id: 'g-anarkali', who: 'girl', name: 'Anarkali', culture: 'North India', top: 'anarkali', topColor: '#c7254e', trim: '#f2c14e', sleeve: 'full', hem: 'ankle', lower: 'churidar', lowerColor: '#f2c14e', head: { style: 'hijab', color: '#f2c14e' }, outer: { style: 'dupatta', color: '#ffd98a' }, pattern: 'bands' },
  { id: 'g-pavadai', who: 'girl', name: 'Pavadai Davani', culture: 'South India', top: 'blouse', topColor: '#2e7d4f', trim: '#e8b93a', sleeve: 'elbow', hem: 'floor', lower: 'skirt', lowerColor: '#8e2b6a', layer: '#2e7d4f', head: { style: 'hijab', color: '#f6c85f' }, outer: { style: 'dupatta', color: '#f6a03a' }, pattern: 'bands', note: 'Langa voni: long silk skirt with zari border, blouse, draped half-sari.' },
  { id: 'g-angrakha', who: 'girl', name: 'Angrakha', culture: 'Mughal', top: 'angrakha', topColor: '#fbf3e4', trim: '#b8862b', sleeve: 'full', hem: 'ankle', lower: 'salwar', lowerColor: '#7a1f3d', head: { style: 'hijab', color: '#7a1f3d' }, outer: { style: 'dupatta', color: '#e7c77a' }, pattern: 'floral' },
  { id: 'g-kurung', who: 'girl', name: 'Baju Kurung', culture: 'Indonesia', top: 'tunic', topColor: '#f7a8b8', trim: '#8a3a5e', sleeve: 'full', hem: 'floor', lower: 'straight-skirt', lowerColor: '#6a3d1f', head: { style: 'hijab', color: '#fbe3ea' }, pattern: 'dots', note: 'Long tunic over a batik skirt.' },
  { id: 'g-kebaya', who: 'girl', name: 'Kebaya', culture: 'Indonesia', top: 'kebaya', topColor: '#fff8ec', trim: '#c79a3b', sleeve: 'full', hem: 'floor', lower: 'straight-skirt', lowerColor: '#3a4f7a', fit: 'fitted', head: { style: 'hijab-wrap', color: '#c79a3b' }, pattern: 'floral' },
  { id: 'g-galabeya', who: 'girl', name: 'Galabeya', culture: 'Egypt', top: 'abaya', topColor: '#2a6f97', trim: '#f2c14e', sleeve: 'full', sleeveShape: 'bell', hem: 'floor', lower: 'none', lowerColor: '#1d4e6b', head: { style: 'hijab', color: '#eadbc8' }, pattern: 'geometric' },
  { id: 'g-abaya', who: 'girl', name: 'Embroidered Abaya', culture: 'Middle East', top: 'abaya', topColor: '#2b2238', trim: '#d4af37', sleeve: 'full', sleeveShape: 'bell', hem: 'floor', lower: 'none', lowerColor: '#2b2238', head: { style: 'hijab-wrap', color: '#3a2f4d' }, pattern: 'geometric' },
  { id: 'g-nomad', who: 'girl', name: 'Desert Wraps', culture: 'Desert Tribes', top: 'robe', topColor: '#d9a066', trim: '#8c3b2a', sleeve: 'full', hem: 'floor', lower: 'none', lowerColor: '#b5763f', head: { style: 'hijab-wrap', color: '#8c3b2a' }, outer: { style: 'shawl', color: '#f1d3a2' }, pattern: 'stripes' },
  { id: 'g-bunad', who: 'girl', name: 'Bunad', culture: 'Norway', top: 'bodice', topColor: '#1f3f73', trim: '#d8342c', sleeve: 'full', hem: 'ankle', lower: 'skirt', lowerColor: '#1f3f73', layer: '#fbfbf5', head: { style: 'hijab', color: '#fbfbf5' }, outer: { style: 'apron', color: '#fbfbf5' }, pattern: 'floral', note: 'Wool bunad with floral embroidery on bodice and skirt.' },
  { id: 'g-dirndl', who: 'girl', name: 'Dirndl (merged)', culture: 'Switzerland', top: 'bodice', topColor: '#2f6b3a', trim: '#f2f2f2', sleeve: 'short', hem: 'midi', lower: 'skirt', lowerColor: '#b9304a', neckline: 'open', fit: 'fitted', layer: '#f7f4ec', head: { style: 'none', color: '#f7f4ec' }, outer: { style: 'apron', color: '#f2d0da' }, pattern: 'stripes', note: 'Reference is short-sleeved, mid-length and fitted; merged with blouse sleeves, trousers and a scarf.' },
  { id: 'g-trench', who: 'girl', name: 'London Trench', culture: 'London', top: 'coat', topColor: '#c9a46a', trim: '#6b4a2b', sleeve: 'full', hem: 'ankle', lower: 'trousers', lowerColor: '#2d2d3a', head: { style: 'hijab', color: '#8a2b3a' }, pattern: 'none' },
  { id: 'g-street', who: 'girl', name: 'City Layers', culture: 'New York', top: 'hoodie', topColor: '#ffcf5c', trim: '#2c2c2c', sleeve: 'full', hem: 'knee', lower: 'trousers', lowerColor: '#556b4a', head: { style: 'hijab', color: '#2c2c2c' }, pattern: 'none' },
  { id: 'g-teadress', who: 'girl', name: 'Tea Dress (merged)', culture: 'Vintage', top: 'gown', topColor: '#9fd3c7', trim: '#f4f1de', sleeve: 'cap', hem: 'midi', lower: 'skirt', lowerColor: '#9fd3c7', layer: '#f4f1de', head: { style: 'wide-hat', color: '#e07a5f' }, pattern: 'dots', note: '1950s tea dress; merged with sleeves, trousers, and a scarf under the hat.' },
  { id: 'g-renaissance', who: 'girl', name: 'Renaissance Gown', culture: 'Renaissance', top: 'gown', topColor: '#7b2d43', trim: '#d4a64a', sleeve: 'full', sleeveShape: 'bell', hem: 'floor', lower: 'skirt', lowerColor: '#7b2d43', neckline: 'open', head: { style: 'hijab', color: '#e9d8b4' }, outer: { style: 'cape', color: '#2e4a3d' }, pattern: 'bands' },
  { id: 'g-parka', who: 'girl', name: 'Aurora Parka', culture: 'Arctic', top: 'parka', topColor: '#e8eef5', trim: '#6ec6c2', sleeve: 'full', hem: 'ankle', lower: 'trousers', lowerColor: '#3b4f6b', head: { style: 'hood', color: '#e8eef5' }, pattern: 'bands' },
  { id: 'g-star', who: 'girl', name: 'Starlight Cloak', culture: 'Fantasy', top: 'robe', topColor: '#23305c', trim: '#ffd86b', sleeve: 'full', sleeveShape: 'wide', hem: 'floor', lower: 'none', lowerColor: '#23305c', head: { style: 'hood', color: '#23305c' }, outer: { style: 'cloak', color: '#3a4d8f' }, pattern: 'stars' },
  { id: 'g-petal', who: 'girl', name: 'Petal Robe', culture: 'Fantasy', top: 'robe', topColor: '#ffd1e3', trim: '#ff8fb8', sleeve: 'full', sleeveShape: 'bell', hem: 'floor', lower: 'none', lowerColor: '#ffd1e3', head: { style: 'hijab-wrap', color: '#fff0f6' }, outer: { style: 'cape', color: '#c4f0d8' }, pattern: 'floral' },
  { id: 'g-nova', who: 'girl', name: 'Nova Suit', culture: 'Sci-fi', top: 'suit', topColor: '#e9edf2', trim: '#3ef0ff', sleeve: 'full', hem: 'ankle', lower: 'trousers', lowerColor: '#b9c3cf', head: { style: 'hood', color: '#dfe6ee' }, outer: { style: 'cloak', color: '#8fa3ba' }, pattern: 'glow' },

  // ───────────── Boy ─────────────
  { id: 'b-meadow', who: 'boy', name: 'Wanderer', culture: 'Meadow', top: 'kurta', topColor: '#8fb3d9', trim: '#3c5a80', sleeve: 'full', hem: 'knee', lower: 'trousers', lowerColor: '#e8dcc2', head: { style: 'hair', color: '#2b1d14' }, outer: { style: 'vest', color: '#5f7a4a' }, pattern: 'none' },
  { id: 'b-kimono', who: 'boy', name: 'Kimono & Haori', culture: 'Japan', top: 'kimono', topColor: '#2f3e5c', trim: '#c9a86a', sleeve: 'full', sleeveShape: 'wide', hem: 'ankle', lower: 'hakama', lowerColor: '#5b5b66', head: { style: 'hair', color: '#1a1410' }, outer: { style: 'haori', color: '#1d2638' } },
  { id: 'b-hanbok', who: 'boy', name: 'Baji Jeogori', culture: 'Korea', top: 'jeogori', topColor: '#d7e8f0', trim: '#3f6c8f', sleeve: 'full', hem: 'ankle', lower: 'trousers', lowerColor: '#f2efe6', head: { style: 'gat', color: '#1c1c1c' }, outer: { style: 'vest', color: '#3f6c8f' } },
  { id: 'b-hanfu', who: 'boy', name: 'Scholar Robe', culture: 'China', top: 'hanfu', topColor: '#e8e2cf', trim: '#2e4c6d', sleeve: 'full', sleeveShape: 'wide', hem: 'floor', lower: 'none', lowerColor: '#c9c1a8', head: { style: 'hair', color: '#1a1410' }, outer: { style: 'sash', color: '#2e4c6d' } },
  { id: 'b-sherwani', who: 'boy', name: 'Sherwani', culture: 'North India', top: 'sherwani', topColor: '#f1e2c3', trim: '#b8862b', sleeve: 'full', hem: 'knee', lower: 'churidar', lowerColor: '#fbf6ea', head: { style: 'turban', color: '#c7254e' }, pattern: 'bands' },
  { id: 'b-kurta', who: 'boy', name: 'Kurta Pyjama', culture: 'South Asia', top: 'kurta', topColor: '#fbfaf5', trim: '#d9b36b', sleeve: 'full', hem: 'knee', lower: 'trousers', lowerColor: '#fbfaf5', head: { style: 'kufi', color: '#fbfaf5' } },
  { id: 'b-pathani', who: 'boy', name: 'Pathani', culture: 'South Asia', top: 'kurta', topColor: '#556b5a', trim: '#2f3b33', sleeve: 'full', hem: 'knee', lower: 'salwar', lowerColor: '#556b5a', head: { style: 'hair', color: '#2b1d14' }, outer: { style: 'vest', color: '#2f3b33' } },
  { id: 'b-veshti', who: 'boy', name: 'Veshti & Kurta', culture: 'South India', top: 'kurta', topColor: '#fdfbf2', trim: '#d4a93a', sleeve: 'full', hem: 'knee', lower: 'wrap', lowerColor: '#fdfbf2', layer: '#efe7d2', head: { style: 'hair', color: '#1a1410' }, outer: { style: 'shawl', color: '#d4a93a' }, pattern: 'bands' },
  { id: 'b-jama', who: 'boy', name: 'Mughal Jama', culture: 'Mughal', top: 'angrakha', topColor: '#fff8e6', trim: '#2f7a5a', sleeve: 'full', hem: 'ankle', lower: 'churidar', lowerColor: '#c23b3b', head: { style: 'turban', color: '#2f7a5a' }, outer: { style: 'sash', color: '#c23b3b' }, pattern: 'floral' },
  { id: 'b-melayu', who: 'boy', name: 'Baju Melayu', culture: 'Indonesia', top: 'kurta', topColor: '#2b8a7e', trim: '#e2c275', sleeve: 'full', hem: 'knee', lower: 'trousers', lowerColor: '#2b8a7e', head: { style: 'songkok', color: '#1b1b1b' }, outer: { style: 'sash', color: '#e2c275' }, pattern: 'geometric' },
  { id: 'b-galabeya', who: 'boy', name: 'Galabeya', culture: 'Egypt', top: 'thobe', topColor: '#d8c7a3', trim: '#6b4f2a', sleeve: 'full', hem: 'floor', lower: 'none', lowerColor: '#d8c7a3', head: { style: 'turban', color: '#f6f1e6' }, outer: { style: 'shawl', color: '#8a6a3f' } },
  { id: 'b-thobe', who: 'boy', name: 'Thobe & Bisht', culture: 'Middle East', top: 'thobe', topColor: '#fbfbf8', trim: '#c9a44a', sleeve: 'full', hem: 'floor', lower: 'none', lowerColor: '#fbfbf8', head: { style: 'ghutra', color: '#f7f7f7' }, outer: { style: 'bisht', color: '#3b2a1c' } },
  { id: 'b-nomad', who: 'boy', name: 'Desert Wraps', culture: 'Desert Tribes', top: 'robe', topColor: '#2f4a6b', trim: '#d9a066', sleeve: 'full', hem: 'floor', lower: 'none', lowerColor: '#2f4a6b', head: { style: 'turban', color: '#2f4a6b' }, outer: { style: 'shawl', color: '#d9a066' }, pattern: 'stripes' },
  { id: 'b-bunad', who: 'boy', name: 'Bunad', culture: 'Norway', top: 'doublet', topColor: '#fbfbf5', trim: '#b0322a', sleeve: 'full', hem: 'knee', lower: 'trousers', lowerColor: '#262b3a', head: { style: 'hair', color: '#c79a5b' }, outer: { style: 'vest', color: '#b0322a' }, note: 'Knee breeches merged into full trousers.' },
  { id: 'b-alpine', who: 'boy', name: 'Alpine Jacket', culture: 'Switzerland', top: 'coat', topColor: '#4a6b3a', trim: '#e8e2d0', sleeve: 'full', hem: 'knee', lower: 'trousers', lowerColor: '#5a4632', head: { style: 'wide-hat', color: '#3a4f2c' }, outer: { style: 'vest', color: '#b9304a' } },
  { id: 'b-coat', who: 'boy', name: 'Wool Coat', culture: 'London', top: 'coat', topColor: '#3a3f4f', trim: '#a8a8b3', sleeve: 'full', hem: 'knee', lower: 'trousers', lowerColor: '#2a2a33', head: { style: 'cap', color: '#6b5a4a' } },
  { id: 'b-street', who: 'boy', name: 'City Layers', culture: 'New York', top: 'hoodie', topColor: '#3a6ea5', trim: '#f2f2f2', sleeve: 'full', hem: 'knee', lower: 'trousers', lowerColor: '#3d3d3d', head: { style: 'beanie', color: '#f2a541' } },
  { id: 'b-vintage', who: 'boy', name: 'Vintage Suit', culture: 'Vintage', top: 'coat', topColor: '#8a6d4b', trim: '#e9d9b8', sleeve: 'full', hem: 'knee', lower: 'trousers', lowerColor: '#8a6d4b', head: { style: 'wide-hat', color: '#4b3a2a' }, outer: { style: 'vest', color: '#e9d9b8' } },
  { id: 'b-renaissance', who: 'boy', name: 'Doublet & Cloak', culture: 'Renaissance', top: 'doublet', topColor: '#2e4a3d', trim: '#d4a64a', sleeve: 'full', hem: 'knee', lower: 'trousers', lowerColor: '#4a3a2a', head: { style: 'cap', color: '#7b2d43' }, outer: { style: 'cloak', color: '#7b2d43' } },
  { id: 'b-parka', who: 'boy', name: 'Aurora Parka', culture: 'Arctic', top: 'parka', topColor: '#3b4f6b', trim: '#e8eef5', sleeve: 'full', hem: 'knee', lower: 'trousers', lowerColor: '#2a3344', head: { style: 'hood', color: '#3b4f6b' }, pattern: 'bands' },
  { id: 'b-moon', who: 'boy', name: 'Moon Cloak', culture: 'Fantasy', top: 'robe', topColor: '#1e2a44', trim: '#bfe3ff', sleeve: 'full', sleeveShape: 'wide', hem: 'floor', lower: 'none', lowerColor: '#1e2a44', head: { style: 'hood', color: '#1e2a44' }, outer: { style: 'cloak', color: '#2d4066' }, pattern: 'stars' },
  { id: 'b-nova', who: 'boy', name: 'Nova Coat', culture: 'Sci-fi', top: 'suit', topColor: '#2a3140', trim: '#3ef0ff', sleeve: 'full', hem: 'ankle', lower: 'trousers', lowerColor: '#1b2029', head: { style: 'hair', color: '#1a1410' }, outer: { style: 'cloak', color: '#3a4458' }, pattern: 'glow' },
];

const ALL: Design[] = [...DESIGNS, ...EXTENDED_DESIGNS];
export const OUTFITS: Record<string, Outfit> = Object.fromEntries(ALL.map((d) => [d.id, modestify(d)]));
export const DESIGN_REFERENCES: readonly Design[] = ALL;
export const outfitsFor = (who: 'girl' | 'boy') => Object.values(OUTFITS).filter((o) => o.who === who);
